--
-- PostgreSQL database dump
--

\restrict DQuyVHKJE9vrHZfKSSeJ33PHNOJdcKOH8PxgIcqqZP0BwPHBOucyhICgp2jQyFq

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

-- Started on 2026-09-04 16:21:53

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 16430)
-- Name: estudos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.estudos (
    id integer NOT NULL,
    materia_id integer,
    assunto character varying(100),
    data date,
    horas numeric
);


ALTER TABLE public.estudos OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16443)
-- Name: estudos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.estudos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.estudos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16424)
-- Name: materias; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.materias (
    id integer NOT NULL,
    nome character varying(100)
);


ALTER TABLE public.materias OWNER TO postgres;

--
-- TOC entry 5013 (class 0 OID 16430)
-- Dependencies: 220
-- Data for Name: estudos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.estudos (id, materia_id, assunto, data, horas) FROM stdin;
10	3	Bancos Relacionais	2026-09-02	4
11	1	Pandas	2026-09-03	3
12	2	Ponteiros	2026-09-03	2
\.


--
-- TOC entry 5012 (class 0 OID 16424)
-- Dependencies: 219
-- Data for Name: materias; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.materias (id, nome) FROM stdin;
1	Python
2	C
3	SQL
\.


--
-- TOC entry 5020 (class 0 OID 0)
-- Dependencies: 221
-- Name: estudos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.estudos_id_seq', 13, true);


--
-- TOC entry 4863 (class 2606 OID 16437)
-- Name: estudos estudos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.estudos
    ADD CONSTRAINT estudos_pkey PRIMARY KEY (id);


--
-- TOC entry 4861 (class 2606 OID 16429)
-- Name: materias materias_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.materias
    ADD CONSTRAINT materias_pkey PRIMARY KEY (id);


--
-- TOC entry 4864 (class 2606 OID 16438)
-- Name: estudos estudos_materia_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.estudos
    ADD CONSTRAINT estudos_materia_id_fkey FOREIGN KEY (materia_id) REFERENCES public.materias(id);


-- Completed on 2026-09-04 16:21:54

--
-- PostgreSQL database dump complete
--

\unrestrict DQuyVHKJE9vrHZfKSSeJ33PHNOJdcKOH8PxgIcqqZP0BwPHBOucyhICgp2jQyFq

